### PR TITLE
Feature/update accessions

### PR DESCRIPTION
**Pull request by suhaibMo**
In this PR,

- Improved this logic for ENAD accessioning and expand to CURD studies that identifies latest accession looking into bulk and single-cell ongoing and loaded studies.
- Make a generic counter script with args for example auto_accessio.sh <Type>. Type could be ENAD or CURD.
 Removed the need to specify atlasprd3 pro as arguments. So can it can work this out itself.

Jenkins job is implemented for user-friendly automation for curation.
http://193.62.54.19:30004/jenkins/view/Curation/job/automate_accession/

### CODE REVIEW

**Comment by anjaf** [comment]
I didn't check the code but ran some tests in Jenkins. The mechanism doesn't quite work as expected yet. 

Issue 1: CURD doesn't show the latest, it's E-CURD-58. But the output I got was E-CURD-55. 
Issue 2: When we run the job for the second time, we should get an incremented accession. Now, I'm getting E-ENAD-48 twice. What I would expect is to get E-ENAD-48 in the first run, and then the next accession E-ENAD-49 in the subsequent job. 

What curators currently do to reserve an accession number, is to manually create a folder in the respective loading directory, `<AE_loading_dir>/CURD/ `and `<ATLAS_PROD>/ENA_import/ENAD/`. 
It would be nice if the mechanism could also create an empty folder for each newly minted accession there as reference.
And then, removing the folder manually would free back up the accession. 

Alternatively, another job to "give back" an accession, thus decrease the counter, would be awesome to have. So that there is a way to reverse the action in case the minted accession is not needed after all.

**Comment by suhaibMo** [comment]
@anjaf Thanks for checking. 

Issue 1: Can you mention where E-CURD-56 to E-CURD-58 are curated and stored?
Issue2: The idea is to get new accession for curators to use. For ENAD Jenkins is showing E-ENAD-48 which is not right. As E-ENAD-48 is already curated and loaded ?

**Comment by anjaf** [comment]
Issue 1: These latest ones are single cell experiments, and are here: https://gitlab.ebi.ac.uk/ebi-gene-expression/scxa-metadata/-/tree/master/CURD 
We also have placeholder folders for them in the <AE_loading_dir>/CURD/ directory. 

Issue 2: Yes, E-ENAD-48 would be the next free accession to use. But it takes time to create the files and place them in the areas where they get registered, e.g. get merge request approved for single cell data to go on to the master branch in the metadata repo. In the meantime, another curator may need to mint an accession, thus they would also see E-ENAD-48 and run with that. Then we have a clash. Therefore, as soon as one accession got minted, the next time we run the pipeline, we should get the incremented accession, not the same one again.

**Comment by suhaibMo** [comment]
@anjaf The scripts pokes into different places including DBs to find the latest CURD study. 
Latest single cells are `$ATLAS_PROD/singlecell/scxa-metadata`. 
Ideally, at present, the job should output E-CURD-59 and E-ENAD-48 respectively when executing the job is it right? as last ones curated were E-CURD-58 and E-ENAD-47 ?

**Comment by anjaf** [comment]
> Latest single cells are $ATLAS_PROD/singlecell/scxa-metadata.

No, this is not the case any more. The GitLab repository is the source of truth for all single-cell experiments. 


> Ideally, at present, the job should output E-CURD-59 and E-ENAD-48 respectively when executing the job is it right?

Yes, but only on the first occasion. If I would trigger another ENAD/CURD job after that, I want to see E-ENAD-49 and E-CURD-50, without the need for the experiments E-CURD-59 and E-ENAD-48 to exist in their pick-up locations. If the script only looks up what files are there on the file system, we don't need an accessioning mechanism. This we can do manually ourselves. The problem that we want to solve with the automatic accessioning is that we need to secure the accessions we minted while working on completing the MAGE-TAB files, and allow easy collaboration without producing clashing accessions. I thought there were some reference IDs stored in the database that hold the latest minted accession and can be used to create these virtual accessions.

**Comment by suhaibMo** [comment]
@anjaf that is right we do secure accession latest accessions in the `reference_ids` table in atlasprd3 database to access directly. This logic is pertinent. What I don't want is every time you build this accession numbering should increment automatically even if there is no experiment exist. 

As of now what is showing in Jenkins will reflect in DB 

image

I will revise the logic to reflect the correct accession ids.

**Comment by suhaibMo** [comment]
@anjaf Ok this fixed now. Jenkins build will show which is next accession and also record in the table reference_ids

next accession,
E-CURD-59
E-ENAD-48
image

**Comment by suhaibMo** [comment]
Now Jenkins output will display two ids. Current maximum curated id, Next accession that curator needs to consider for naming for a new study 
Example for `CURD`
image

**Comment by anjaf** [comment]
Thanks Suhaib, It's showing now the correct/latest accession. 

But you might have slightly misunderstood the second point. It wasn't about showing the current and the next ID. In fact, could you please remove the output of the current ID again? (this may lead to mistakes when copy/pasting the wrong accession)

What I meant was that when I submit two Jenkins jobs for the same type, I want to get incremental accessions. If I ran it three times, I want 3 increasing accessions. Let's say E-ENAD is at 60. I trigger 3 ENAD Jenkins runs and want to get returned E-ENAD-61, E-ENAD-62, E-ENAD-63. If I did that now, I would get E-ENAD-61 every time. 

>What I don't want is every time you build this accession numbering should increment automatically even if there is no experiment exist. 

Well, but this is what curators are asking for. For the reasons explained above it doesn't help us much to only look up the latest accession that has been already loaded. We need to be able to mint and reserve accessions for experiments that don't exist yet.
What is the purpose of storing the reference_id if it is not used to increment and generate new accession? This is the easiest logic and all we need really.

**Comment by pcm32** [comment]
Maybe the easiest here would be to add a flag to the experiment table in both SC and Bulk databases, and then start tracking accessions there (and then each requests adds a new identifier appropriately on that table). That would become the single source of identifiers, and you don't need to be dealing with multiple locations on dbs, file systems, etc. You still need an identifier to add elements to the metadata repo in Gitlab, so I wouldn't see an issue here.

The main downside would be that the web application would need to filter those hits out on its queries (through the flag that I mentioned, so we would need to have at least a release on wwwdev with that change), but I would expect that only a few queries from the web application would require changes. Please ignore me if this has been considered before and neglected for some major reason.

**Review by anjaf — APPROVED** [review]
We decided that the accessioning logic change need to be another task. Approving the current behaviour as it is designed to show the latest/highest accession already in use.

**Comment by suhaibMo** [comment]
Thank you @anjaf and @pcm32 for the review and comments.

**Pull request merged**
